name: FGO Login System

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/O-Isaac/FGO-Daily-Login/master/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v2

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: 22139125
          authKeys: 5d0kg0I19fL1jY7t:9dBRAQAAAAA=
          secretKeys: Sd3mpSPKM/6fp9uO:9dBRAQAAAAA=
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
